name: Lint
on:
  - pull_request

jobs:
  lint_ts:
    name: Lint TypeScript source
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
        with:
          python_version: "3.11.x"
      - name: Install JupyterLab
        run: pip install jupyterlab~=4.0
      - name: Install JS dependencies
        run: jlpm
      - name: Lint TypeScript source
        run: jlpm lerna run lint:check
