name: Lint
on:
  - pull_request

jobs:
  lint_ts:
    name: Lint TypeScript source
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
        with:
          python_version: "3.11.x"
      - name: Install JupyterLab
        run: pip install jupyterlab~=4.0
      - name: Install JS dependencies
        run: jlpm
      - name: Lint TypeScript source
        run: jlpm lerna run lint:check

  lint_py_imports:
    name: Lint Python imports
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Echo environment details
        run: |
          which python
          which pip
          python --version
          pip --version

      # see #546 for context on why this is necessary
      - name: Create venv
        run: |
          python -m venv lint_py_imports

      - name: Install job dependencies
        run: |
          source ./lint_py_imports/bin/activate
          pip install jupyterlab~=4.0
          pip install import-linter~=1.12.1

      - name: Install Jupyter AI packages from source
        run: |
          source ./lint_py_imports/bin/activate
          jlpm install
          jlpm install-from-src

      - name: Lint Python imports
        run: |
          source ./lint_py_imports/bin/activate
          lint-imports
